name: main # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master

jobs:
  auto_update_code_job:
    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    steps:
      - name: update code
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: cd /root/project/resume && git checkout . && git pull
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
